# Generated by Django 3.0.2 on 2020-01-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200108_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='s_1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_10',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_11',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_12',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_13',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_14',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_15',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_16',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_17',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_18',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_19',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_2',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_20',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_3',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_4',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_5',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_6',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_7',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_8',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='s_9',
            field=models.IntegerField(default=-1),
        ),
    ]
