# Generated by Django 3.0.2 on 2020-01-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200108_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_11',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_12',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_13',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_14',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_15',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_16',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_17',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_18',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_19',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_20',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_9',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
