# Generated by Django 3.0.2 on 2020-01-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200113_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='result',
            field=models.CharField(max_length=100),
        ),
    ]
